<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Helpdesk</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Helpdesk.Domain\Helpdesk.Domain.csproj" />
    <ProjectReference Include="..\Helpdesk.Application.Contracts\Helpdesk.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net" Version="3.18.0" />
    <PackageReference Include="MiniExcel" Version="1.46.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Account.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="10.6.0" />
  </ItemGroup>

</Project>
